### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by dbof10** [dotanuki-labs/norris#1]
```
private fun interpret(interaction: UserInteraction) =
        when (interaction) {
            OpenedScreen, RequestedFreshContent -> ::showFacts
            is NewSearch -> {
                currentQuery = (interaction as NewSearch).query
                ::showFacts
            }
            else -> throw UnsupportedUserInteraction
        }

    private suspend fun showFacts() =
        usecase.search(currentQuery)
            .map { FactDisplayRow(it) }
            .let { rows ->
                FactsPresentation(currentQuery, rows)
            }
```
with the current arch the app is using. Is there anyway to pass parameter to `showFacts` like
```showFacts(query: String)```. Look at the code, you have to keep `currentQuery` as a global field. I don't think that looks good

**Comment by ubiratansoares** [comment]
@dbof10 I'm aware of it, and I'm not 100% happy with this design as well. 

The actual problem is :  StateMachine#forward can only take a 

```suspend ()->T```

as transition event; I want to find a way to let it support at least a 

```
suspend (U) -> T
```

without messing with the actual implementation and without (that much) boilerplate as well ...

I'm working on it, and I'm accepting suggestions as well

**Comment by ubiratansoares** [comment]
@dbof10 I found a way to provide a more flexible API to StateMachine, introducing the concept of a `StateTransition`.

I also added an abstraction name `CommandProcessor`, once I reworked the way the selected query is actually passed from the Search screen to the Facts screen. Such abstraction is intended to push commands for a View layer (pretty much navigation ones)

I'm closing this issue for now, once both ViewModels (Facts and Search) does not have any mutable internal state anymore
